version: "3"
volumes:
  prometheus_data:

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass 1234 --appendonly yes
    hostname: localhost
    ports:
      - 6379:6379
    volumes:
      - "./redis/supermarket:/var/lib/postgresql/data"
    networks:
      - redis
  postgres:
    image: postgres:9.6
    container_name: "supermarket-acme"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./data/supermarket/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      - postgres
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - zippkin
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    volumes:
#      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yml"
#    ports:
#      - "9090:9090"
#    networks:
#      - prometheus
networks:
  zippkin:
    driver: bridge
  postgres:
    driver: bridge
  rabbitmq:
    driver: bridge
#  prometheus:
#    driver: bridge
  redis:
    driver: bridge
