
version: "3"
services:
  postgres:
    image: postgres:9.6
    container_name: "supermarket-acme"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./data/supermarket/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      - postgres
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - zippkin
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq

networks:
  zippkin:
    driver: bridge
  postgres:
    driver: bridge
  rabbitmq:
    driver: bridge
